version: "3.7"

services:
  emailer:
    image: emailer:latest
    build: .
    container_name: emailer
    restart: unless-stopped
    environment:
      - SENDER_EMAIL={SENDER_EMAIL}
      - SENDER_PASSWORD={SENDER_PASSWORD}
